package Vistas;
/**
 */
public class jpComponente extends javax.swing.JPanel {

    /** Creates new form jpComponente */
    public jpComponente()  {
        initComponents();
        //JPanel
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        this.setSize(230, 30);
        this.setVisible(true);//se agrega un comando al boton
     
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioRespuesta = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridBagLayout());

        radioRespuesta.setText("111111111111111111111111111111111111111");
        add(radioRespuesta, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton radioRespuesta;
    // End of variables declaration//GEN-END:variables



}
